M48
; DRILL file {KiCad 9.0.2} date 2025-06-19T00:07:11-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-19T00:07:11-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
%
G90
G05
T1
G00X163.5Y-60.8
M15
G01X163.5Y-59.8
M16
G05
G00X168.5Y-67.0
M15
G01X167.5Y-67.0
M16
G05
M30
